[mypy]
python_version = 3.11
warn_return_any = True
warn_unused_configs = True
ignore_missing_imports = True
check_untyped_defs = False
no_implicit_optional = False
disallow_untyped_defs = False
exclude = (?x)(
    ^test_.*$
    | ^tests/.*$
    | ^debug_.*$
    | ^update_test_.*$
    | ^init_vector_db\.py$
    | ^bot_endpoints\.py$
  )

[mypy-main]
ignore_errors = True

[mypy-models]
ignore_errors = True

[mypy-database]
ignore_errors = True

[mypy-processor]
ignore_errors = True

[mypy-ingestion_service]
ignore_errors = True
